import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");
const studio=await readFile(new URL("../app/teacher-problem-studio-pro.tsx",import.meta.url),"utf8");
const input=await readFile(new URL("../app/math-input.tsx",import.meta.url),"utf8");
const keyboard=await readFile(new URL("../app/math-keyboard.tsx",import.meta.url),"utf8");
const formula=await readFile(new URL("../app/math-formula.tsx",import.meta.url),"utf8");
const layout=await readFile(new URL("../app/layout.tsx",import.meta.url),"utf8");
const learningCss=await readFile(new URL("../app/learning-flow.css",import.meta.url),"utf8");
test("기존 학생 정보 localStorage 키를 유지한다",()=>assert.match(page,/oedong-student-info/));
test("기존 교사 비밀번호 localStorage 키를 유지한다",()=>assert.match(page,/oedong-teacher-password/));
test("기존 탑재 상태 localStorage 키를 유지한다",()=>assert.match(page,/oedong-uploaded-mounted/));
test("기존 문제 검수 저장·삭제 기능을 유지한다",()=>{assert.match(page,/saveQuestion/);assert.match(page,/deleteProblem/)});
test("기존 문제 보관함 개별 삭제 기능을 유지한다",()=>assert.match(studio,/problems\.filter\(x=>x\.id!==p\.id\)/));
test("기존 문제는 판정 설정이 선택 사항이다",()=>assert.match(studio,/judgeRules\?:JudgeRules/));
test("판정 시험 통과 전 완료 저장을 막는다",()=>assert.match(studio,/if\(!judgeVerified\)/));
test("공용 수식판 삭제·실행취소·다시실행·접기 기능을 유지한다",()=>{for(const label of ["한 글자","실행 취소","다시 실행","수식판 닫기"])assert.match(keyboard,new RegExp(label))});
test("앱 최상위에 공용 수식판 인스턴스를 하나만 둔다",()=>{assert.match(layout,/MathKeyboardProvider/);assert.equal((layout.match(/<MathKeyboardProvider>/g)??[]).length,1)});
test("KaTeX는 안전한 공용 표시 컴포넌트에서만 렌더링한다",()=>{assert.match(formula,/katex\.renderToString/);assert.match(formula,/throwOnError:false/);assert.match(formula,/trust:false/);assert.match(formula,/htmlAndMathml/)});
test("시범 수식은 CSS 슬래시 조립 대신 명시적 LaTeX를 사용한다",()=>{assert.match(formula,/\\\\frac\{x\}\{4\}\+7=10/);assert.match(page,/pilotMathParts\(currentPiece\.q\)/)});
test("유형문제에서 이전 단계와 처음으로를 사용할 수 있다",()=>{assert.match(page,/"이전 단계"/);assert.match(page,/>처음으로</)});
test("모든 본문제 재도전 화면에서 이전 발문으로 돌아갈 수 있다",()=>{assert.match(page,/className="retryPrevious"/);assert.match(page,/setPiecesComplete\(false\)/);assert.match(page,/setPieceIndex\(Math\.max\(0,p\.pieces\.length-1\)\)/)});
test("같은 유형 단계에서 본문제를 숨기고 전체 폭을 사용한다",()=>{assert.match(learningCss,/body:has\(\.practiceCard\).*\.originalProblem\{display:none!important\}/);assert.match(learningCss,/max-width:1180px/)});
test("같은 유형 문제에 선택 언어 번역 영역을 표시한다",()=>{assert.match(page,/className="practiceTranslation"/);assert.match(page,/practiceTranslation\(item\.q,lang\)/)});
test("같은 유형은 한 문제씩 확인한 뒤 이동한다",()=>{assert.match(page,/practiceIndex/);assert.match(page,/다음 문제 →/);assert.match(page,/practiceChecked/)});
test("같은 유형의 교사 실마리는 선택 언어를 병기한다",()=>{assert.match(input,/coachTranslation/);assert.match(page,/practiceCoach\(practiceIndex,lang\)/)});
test("수식판이 열려도 현재 문제가 고정되어 보인다",()=>{assert.match(learningCss,/\.practiceFocusProblem\{position:sticky/);assert.match(learningCss,/\.practiceFocus \.mathPad\{max-height:320px;overflow:auto/)});
test("선택지 내용은 번호 원형 스타일과 분리한다",()=>assert.match(learningCss,/\.choices button>\.choiceTexts\{width:auto!important/));
test("일반 본문과 번역 분수도 공용 KaTeX 큰 분수로 표시한다",()=>{assert.match(page,/sharedInlineFraction/);assert.match(page,/latex:`\\\\dfrac\{\$\{numerator\}\}\{\$\{denominator\}\}`/);assert.doesNotMatch(page,/textbookFractionNumerator/)});
test("검수되지 않은 다국어 발문을 학생에게 표시하지 않는다",()=>{assert.match(page,/reviewedPilotTranslations\[value\]\?\.\[lang\]\?\?""/);assert.doesNotMatch(page,/genericTranslationStarts/)});
