"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import "./teacher-problem-studio-pro.css";

type Curriculum = Record<string, Record<string, Record<string, string[]>>>;
type Crop = { x:number; y:number; w:number; h:number };
type Problem = { id:string; checked:boolean; number:string; image:string; answer:string; explanation:string; term:string; major:string; middle:string; minor:string; source:string; createdAt:number };
type PdfItem = { id:string; name:string; size:number; url:string };
const KEY="oedong-manual-problems-v2";
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const symbols=["x","y","z","x²","x³","√","π","±","×","÷","=","≠","≤","≥","∠","°","( )","□/□"];

function FormulaInput({value,onChange}:{value:string;onChange:(v:string)=>void}){
  const ref=useRef<HTMLInputElement>(null);
  const put=(s:string)=>{const el=ref.current,a=el?.selectionStart??value.length,b=el?.selectionEnd??value.length;const text=s==="□/□"?"(분자)/(분모)":s;onChange(value.slice(0,a)+text+value.slice(b));requestAnimationFrame(()=>ref.current?.focus())};
  return <div className="formulaBox"><input ref={ref} value={value} onChange={e=>onChange(e.target.value)} placeholder="정답을 입력하거나 붙여넣으세요"/><div>{symbols.map(s=><button type="button" key={s} onClick={()=>put(s)}>{s}</button>)}</div></div>;
}

export default function TeacherProblemStudioPro({curriculum}:{curriculum:Curriculum}){
  const pdfInput=useRef<HTMLInputElement>(null), imageInput=useRef<HTMLInputElement>(null), pasteRef=useRef<HTMLDivElement>(null), canvasRef=useRef<HTMLCanvasElement>(null);
  const terms=Object.keys(curriculum), defaultTerm=terms[0]||"중1 · 1학기", defaultMajor=Object.keys(curriculum[defaultTerm]||{})[0]||"미분류", defaultMiddle=Object.keys(curriculum[defaultTerm]?.[defaultMajor]||{})[0]||"미분류", defaultMinor=curriculum[defaultTerm]?.[defaultMajor]?.[defaultMiddle]?.[0]||"미분류";
  const [tab,setTab]=useState<"work"|"bank">("work"), [pdfs,setPdfs]=useState<PdfItem[]>([]), [pdfId,setPdfId]=useState(""), [raw,setRaw]=useState(""), [crop,setCrop]=useState<Crop>({x:0,y:0,w:1,h:1}), [drag,setDrag]=useState<{x:number;y:number}|null>(null);
  const [number,setNumber]=useState("1"),[answer,setAnswer]=useState(""),[explanation,setExplanation]=useState(""),[problems,setProblems]=useState<Problem[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[activeTool,setActiveTool]=useState<"crop"|"trim">("crop"),[search,setSearch]=useState("");
  const [term,setTerm]=useState(defaultTerm),[major,setMajor]=useState(defaultMajor),[middle,setMiddle]=useState(defaultMiddle),[minor,setMinor]=useState(defaultMinor);
  useEffect(()=>{try{const v=localStorage.getItem(KEY);if(v)setProblems(JSON.parse(v))}catch{}},[]);
  const saveAll=(v:Problem[])=>{setProblems(v);try{localStorage.setItem(KEY,JSON.stringify(v))}catch{setNotice("저장 공간이 부족합니다. 필요 없는 문제를 삭제해 주세요.")}};
  const activePdf=pdfs.find(p=>p.id===pdfId);
  const read=(file:File)=>{const r=new FileReader();r.onload=()=>{setRaw(String(r.result));setCrop({x:0,y:0,w:1,h:1});setActiveTool("crop");setNotice("캡처가 붙었습니다. 테두리를 드래그해 문제만 선택하세요.")};r.readAsDataURL(file)};
  const paste=(e:React.ClipboardEvent)=>{const f=Array.from(e.clipboardData.items).find(x=>x.type.startsWith("image/"))?.getAsFile();if(!f){setNotice("클립보드에 이미지가 없습니다. Shift+Win+S로 캡처한 뒤 Ctrl+V를 누르세요.");return}e.preventDefault();read(f)};
  const pdfFiles=(files:FileList|null)=>{if(!files)return;const next=Array.from(files).map(f=>({id:id(),name:f.name,size:f.size,url:URL.createObjectURL(f)}));setPdfs(v=>[...v,...next]);if(next[0])setPdfId(next[0].id);setNotice(`${next.length}개 PDF를 열었습니다. 왼쪽 원문을 보며 문제를 캡처하세요.`)};
  const pos=(e:React.PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}};
  const down=(e:React.PointerEvent)=>{if(!raw)return;e.currentTarget.setPointerCapture(e.pointerId);const p=pos(e);setDrag(p);setCrop({x:p.x,y:p.y,w:0,h:0});setActiveTool("crop")};
  const move=(e:React.PointerEvent)=>{if(!drag)return;const p=pos(e);setCrop({x:Math.min(drag.x,p.x),y:Math.min(drag.y,p.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y)})};
  const finish=()=>setDrag(null);
  const cropped=()=>new Promise<string>((resolve,reject)=>{if(!raw)return reject();const img=new Image();img.onload=()=>{const c=canvasRef.current!;const x=Math.round(crop.x*img.width),y=Math.round(crop.y*img.height),w=Math.max(1,Math.round(crop.w*img.width)),h=Math.max(1,Math.round(crop.h*img.height));c.width=w;c.height=h;const ctx=c.getContext("2d")!;ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.drawImage(img,x,y,w,h,0,0,w,h);resolve(c.toDataURL("image/jpeg",.94))};img.onerror=reject;img.src=raw});
  const store=async()=>{if(!raw){setNotice("먼저 문제 캡처를 붙여넣으세요.");return}if(crop.w<.02||crop.h<.02){setNotice("마우스로 저장할 문제 범위를 넉넉하게 선택하세요.");return}setBusy(true);try{const image=await cropped();const p:Problem={id:id(),checked:true,number:number||String(problems.length+1),image,answer,explanation,term,major,middle,minor,source:activePdf?.name||"화면 캡처",createdAt:Date.now()};saveAll([p,...problems]);setRaw("");setAnswer("");setExplanation("");setNumber(String((Number(number)||problems.length+1)+1));setNotice(`${p.number}번 문제 저장 완료 ✓ 다음 문제를 캡처하세요.`)}finally{setBusy(false)}};
  const autoTrim=()=>{setCrop({x:.025,y:.025,w:.95,h:.95});setActiveTool("trim");setNotice("바깥 여백을 줄였습니다. 파란 테두리를 확인하고 필요하면 다시 드래그하세요.")};
  const filtered=useMemo(()=>problems.filter(p=>`${p.number} ${p.answer} ${p.explanation} ${p.source}`.toLowerCase().includes(search.toLowerCase())),[problems,search]);
  const selector=<div className="simpleSelectors"><label>학년·학기<select value={term} onChange={e=>{const t=e.target.value,m=Object.keys(curriculum[t]||{})[0],d=Object.keys(curriculum[t]?.[m]||{})[0];setTerm(t);setMajor(m);setMiddle(d);setMinor(curriculum[t]?.[m]?.[d]?.[0]||"")}}>{terms.map(x=><option key={x}>{x}</option>)}</select></label><label>대단원<select value={major} onChange={e=>{const m=e.target.value,d=Object.keys(curriculum[term]?.[m]||{})[0];setMajor(m);setMiddle(d);setMinor(curriculum[term]?.[m]?.[d]?.[0]||"")}}>{Object.keys(curriculum[term]||{}).map(x=><option key={x}>{x}</option>)}</select></label><label>중단원<select value={middle} onChange={e=>{setMiddle(e.target.value);setMinor(curriculum[term]?.[major]?.[e.target.value]?.[0]||"")}}>{Object.keys(curriculum[term]?.[major]||{}).map(x=><option key={x}>{x}</option>)}</select></label><label>소단원<select value={minor} onChange={e=>setMinor(e.target.value)}>{(curriculum[term]?.[major]?.[middle]||[]).map(x=><option key={x}>{x}</option>)}</select></label></div>;
  return <section className="manualStudio">
    <header className="manualHero"><div><small>교사 문제 작업실</small><h1>자르고 · 정답과 해설 붙이고 · 저장</h1><p>AI 없이 교사가 확인한 그대로 정확하게 보관합니다.</p></div><b>{problems.length}<span>저장 문제</span></b></header>
    <nav className="manualTabs"><button className={tab==="work"?"selected":""} onClick={()=>setTab("work")}>1. 문제 자르기</button><button className={tab==="bank"?"selected":""} onClick={()=>setTab("bank")}>2. 저장함 ({problems.length})</button></nav>
    {notice&&<div className="manualNotice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {tab==="work"&&<div className="manualLayout">
      <aside className="sourcePane"><div className="paneTitle"><div><b>① PDF 원문</b><span>원문은 왼쪽에 계속 표시됩니다.</span></div><button className="choose" onClick={()=>pdfInput.current?.click()}>PDF 선택</button><input ref={pdfInput} hidden multiple type="file" accept="application/pdf" onChange={e=>pdfFiles(e.target.files)}/></div>{pdfs.length>0&&<select className="pdfSelect" value={pdfId} onChange={e=>setPdfId(e.target.value)}>{pdfs.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>}{activePdf?<iframe src={activePdf.url} title="PDF 원문"/>:<div className="sourceEmpty">PDF를 선택하면 원문이 여기에 크게 표시됩니다.</div>}<p className="sourceHelp">원하는 문제를 <b>Shift+Win+S</b>로 캡처한 뒤 오른쪽 영역에서 <b>Ctrl+V</b> 하세요.</p></aside>
      <main className="editPane"><div className="paneTitle"><div><b>② 문제 붙여넣고 자르기</b><span>파란 테두리 안쪽만 흰 배경으로 저장됩니다.</span></div><span className="stepBadge">문제 {number}</span></div>
        <div ref={pasteRef} tabIndex={0} className={`cropStage ${raw?"ready":""}`} onPaste={paste} onClick={()=>pasteRef.current?.focus()} onPointerDown={down} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}>{raw?<><img src={raw} alt="붙여넣은 문제" draggable={false}/><i style={{left:`${crop.x*100}%`,top:`${crop.y*100}%`,width:`${crop.w*100}%`,height:`${crop.h*100}%`}}/></>:<div><strong>여기를 클릭하고 Ctrl+V</strong><span>또는 캡처 이미지 파일을 선택하세요.</span><button onClick={e=>{e.stopPropagation();imageInput.current?.click()}}>이미지 선택</button></div>}<input ref={imageInput} hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/></div>
        <div className="toolRow"><button className={activeTool==="crop"?"activeTool":""} onClick={()=>{setActiveTool("crop");setNotice("이미지 위에서 저장할 문제 범위를 드래그하세요.")}}>✓ 수동 자르기</button><button className={activeTool==="trim"?"activeTool":""} onClick={autoTrim}>자동 여백 줄이기</button><button onClick={()=>{setCrop({x:0,y:0,w:1,h:1});setActiveTool("crop")}}>원본 범위</button><button className="reset" onClick={()=>setRaw("")}>캡처 삭제</button></div>
        <div className="entryGrid"><label>문제 번호<input value={number} onChange={e=>setNumber(e.target.value)}/></label><label className="answerField">③ 정답<FormulaInput value={answer} onChange={setAnswer}/></label><label className="explainField">④ 해설<textarea value={explanation} onChange={e=>setExplanation(e.target.value)} onPaste={e=>{if(Array.from(e.clipboardData.items).some(x=>x.type.startsWith("image/")))setNotice("해설 이미지는 현재 문제 캡처처럼 이미지로 붙인 뒤 저장할 수 있습니다. 한글 텍스트는 이 칸에 그대로 붙여집니다.")}} placeholder="한글 텍스트를 Ctrl+V로 붙이거나 직접 입력하세요."/></label></div>{selector}
        <div className="saveRow"><button className="draft" onClick={()=>setNotice("현재 입력은 화면에 유지됩니다. 저장하려면 오른쪽 버튼을 누르세요.")}>입력 유지</button><button className={busy?"saving":"saveNext"} disabled={busy} onClick={store}>{busy?"저장 중…":"⑤ 저장하고 다음 문제 →"}</button></div><canvas ref={canvasRef} hidden/>
      </main></div>}
    {tab==="bank"&&<section className="simpleBank"><div className="bankHead"><div><b>문제 저장함</b><span>체크한 문제를 확인하고 개별 삭제할 수 있습니다.</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="문제 번호·정답·파일 검색"/></div>{filtered.length?<div className="savedGrid">{filtered.map(p=><article key={p.id}><header><label><input type="checkbox" checked={p.checked} onChange={e=>saveAll(problems.map(x=>x.id===p.id?{...x,checked:e.target.checked}:x))}/><b>{p.number}번 문제</b></label><button onClick={()=>{if(confirm(`${p.number}번 문제를 삭제할까요?`))saveAll(problems.filter(x=>x.id!==p.id))}}>삭제</button></header><img src={p.image} alt={`${p.number}번 문제`}/><dl><dt>정답</dt><dd>{p.answer||"미입력"}</dd><dt>해설</dt><dd>{p.explanation||"미입력"}</dd></dl><small>{p.term} · {p.major} · {p.middle} · {p.minor}</small></article>)}</div>:<div className="bankBlank">저장된 문제가 없습니다. 문제를 자르고 저장해 주세요.</div>}</section>}
  </section>;
}
